version: "3.8"

services:
  nominatim:
    image: mediagis/nominatim:4.4
    ports:
      - "8080:8080"
    environment:
      NOMINATIM_PGSQL_PASS: osm
    command: sh -c "/app/init.sh && /app/start.sh"
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main

volumes:
  nominatim-data:
